# Site settings
title: nullday
email: chris@nullday.de
description: "nullday is the webspace of Christian Rebischke. Last change: 2018-07-15"
baseurl: ""
url: "http://en.nullday.de"
twitter_username: sh1bumi
github_username:  shibumi
linkedin_username: shibumi
google_plus_username: ChristianRebischke
xing_username: Christian_Rebischke


# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
