# Site settings
title: nullday
email: chris@nullday.de
description: "nullday is the webspace of Christian Rebischke and powered by jekyll without Javascript, PHP, Cookies and MySQL. Last change: 2017-04-09"
baseurl: ""
url: "http://en.nullday.de"
twitter_username: sh1bumi
github_username:  shibumi
linkedin_username: shibumi
google_plus_username: ChristianRebischke
xing_username: Christian_Rebischke


# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
